// <auto-generated />
using JoelHiltonFilm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JoelHiltonFilm.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20220203044617_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("JoelHiltonFilm.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CatName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CatName = "Action"
                        },
                        new
                        {
                            CategoryID = 2,
                            CatName = "Family"
                        },
                        new
                        {
                            CategoryID = 3,
                            CatName = "Adventure"
                        },
                        new
                        {
                            CategoryID = 4,
                            CatName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 5,
                            CatName = "Horror"
                        },
                        new
                        {
                            CategoryID = 6,
                            CatName = "Romance"
                        });
                });

            modelBuilder.Entity("JoelHiltonFilm.Models.FormResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationId");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");
                });

            modelBuilder.Entity("JoelHiltonFilm.Models.FormResponse", b =>
                {
                    b.HasOne("JoelHiltonFilm.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
